flags:
  operator:
    paths:
      - pkg/
coverage:
  status:
    project:
      operator:
        target: auto
        threshold: 5%
        base: auto
        flags:
          - operator
comment:
  require_changes: true